In [4]:
import pandas as pd

collisions_df = pd.read_csv("dft-road-casualty-statistics-collision-2025.csv")
casualties_df = pd.read_csv("dft-road-casualty-statistics-casualty-2025.csv")

In [5]:
collisions_df

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517H102225,2025,17H102225,449216.0,534979.0,-1.23770,54.70743,17,2,3,...,-1,0,2,1,2,E01033467,7,1,1.00000,0.00000
1,2025070815222,2025,070815222,363808.0,389192.0,-2.54576,53.39831,7,3,2,...,-1,0,1,2,2,E01012556,3,1,0.00000,1.00000
2,2025070937984,2025,070937984,362413.0,389071.0,-2.56673,53.39712,7,2,2,...,-1,0,1,3,2,E01012478,7,1,1.00000,0.00000
3,2025041687395,2025,041687395,368238.0,427802.0,-2.48308,53.74562,4,2,1,...,-1,0,1,1,2,E01012655,7,1,1.00000,0.00000
4,2025161555094,2025,161555094,510792.0,432167.0,-0.32035,53.77406,16,3,2,...,-1,0,1,1,2,E01012815,3,1,0.00000,1.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101520,2025622500238,2025,622500238,309591.0,179600.0,-3.30409,51.50807,62,3,2,...,0,13,2,1,-1,W01001729,-1,0,0.19717,0.80283
101521,2025622500335,2025,622500335,316017.0,181049.0,-3.21187,51.52209,62,3,2,...,0,0,1,1,-1,W01001851,-1,0,0.10476,0.89524
101522,2025610038025,2025,610038025,315454.0,186626.0,-3.22133,51.57214,61,3,1,...,0,0,1,1,-1,W01001424,-1,0,0.17878,0.82122
101523,2025610009425,2025,610009425,353274.0,193789.0,-2.67663,51.64095,61,3,1,...,0,0,1,1,-1,W01001587,-1,0,0.15929,0.84071
101524,2025631632945,2025,631632945,309912.0,313706.0,-3.33500,52.71349,63,3,2,...,-1,0,2,1,-1,W01000475,3,1,0.00000,1.00000

In [6]:
casualties_df

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2025010555120,2025,010555120,1,1,3,2,14,3,3,...,0,-1,0,5,E01000194,3,1,0.0,1.0,1
1,2025010555533,2025,010555533,3,1,3,2,48,8,2,...,0,-1,0,3,E01002766,7,1,1.0,0.0,2
2,2025010555864,2025,010555864,1,1,3,1,32,6,3,...,0,0,0,7,E01032781,-1,0,0.0,1.0,1
3,2025010558295,2025,010558295,1,1,3,1,26,6,3,...,0,-1,0,6,E01001494,3,1,0.0,1.0,1
4,2025010558923,2025,010558923,1,1,3,1,41,7,3,...,0,-1,0,-1,-1,3,1,0.0,1.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127878,2025351612912,2025,351612912,2,2,1,2,25,5,3,...,0,0,90,7,E01018286,3,1,0.0,1.0,4
127879,2025991585031,2025,991585031,1,3,2,1,10,2,2,...,0,0,90,1,E01008300,7,1,1.0,0.0,4
127880,2025101663507,2025,101663507,1,1,1,1,18,4,2,...,0,0,97,2,E01008812,7,1,1.0,0.0,1
127881,2025161636644,2025,161636644,2,1,1,1,30,6,2,...,0,0,97,-1,-1,7,1,1.0,0.0,-1
127882,2025461600385,2025,461600385,1,1,1,1,-1,-1,3,...,0,0,97,-1,-1,3,1,0.0,1.0,-1

In [12]:
collisions_df['collision_index'].nunique() == len(collisions_df)

True

In [16]:
mismatched = casualties_df[~casualties_df['collision_index'].isin(collisions_df['collision_index'])]
print(len(mismatched))

0

In [17]:
no_casualties = collisions_df[~collisions_df['collision_index'].isin(casualties_df['collision_index'])]
print(len(no_casualties))

0

In [18]:
casualties_df['casualty_severity'].unique()

array([3, 2, 1])